-- AlterTable
ALTER TABLE "Contribuyente" ADD COLUMN     "agenteRetencion" TEXT DEFAULT 'NO',
ADD COLUMN     "artesano" TEXT DEFAULT 'No registra',
ADD COLUMN     "barrio" TEXT,
ADD COLUMN     "calle" TEXT,
ADD COLUMN     "canton" TEXT,
ADD COLUMN     "celular" TEXT,
ADD COLUMN     "codigoVerificacion" TEXT,
ADD COLUMN     "contribuyenteEspecial" TEXT DEFAULT 'NO',
ADD COLUMN     "direccionIpEmision" TEXT,
ADD COLUMN     "email" TEXT,
ADD COLUMN     "fechaActualizacion" TIMESTAMP(3),
ADD COLUMN     "fechaCeseActividades" TIMESTAMP(3),
ADD COLUMN     "fechaInicioActividades" TIMESTAMP(3),
ADD COLUMN     "fechaRegistro" TIMESTAMP(3),
ADD COLUMN     "fechaReinicioActividades" TIMESTAMP(3),
ADD COLUMN     "interseccion" TEXT,
ADD COLUMN     "jurisdiccion" TEXT,
ADD COLUMN     "numero" TEXT,
ADD COLUMN     "numerosRucAnteriores" TEXT DEFAULT 'No registra',
ADD COLUMN     "obligadoContabilidad" TEXT DEFAULT 'NO',
ADD COLUMN     "parroquia" TEXT,
ADD COLUMN     "provincia" TEXT,
ADD COLUMN     "referencia" TEXT,
ADD COLUMN     "telefonoDomicilio" TEXT,
ADD COLUMN     "tipoAgenteRetencion" TEXT DEFAULT 'PERSONAS NATURALES';
